#undef CONFIG_MLX4_CORE
#define CONFIG_MLX4_CORE 1
#undef CONFIG_MLX4_EN
#define CONFIG_MLX4_EN 1
#undef CONFIG_MLX4_EN_DCB
#define CONFIG_MLX4_EN_DCB 1
#undef CONFIG_MLX5_CORE
#define CONFIG_MLX5_CORE 1


